# Data Manipulation Solutions


## Exercise 1

First, we import torch and define the values of X and Y


In [7]:
import torch
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
X,Y

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([[2., 1., 4., 3.],
         [1., 2., 3., 4.],
         [4., 3., 2., 1.]]))

First, we try X < Y.

In [8]:
X < Y

tensor([[ True, False,  True, False],
        [False, False, False, False],
        [False, False, False, False]])

X and Y are two tensors having the same size and shape, and hence we can use operations like <, > and == on them.

As expected, we get a tensor having only boolean values as an output, containing the result of X < Y. All corresponding elements of X and Y are compared using < operator, and the boolean result of each comparision is stored in the binary tensor.

Since there is one element corresponding to every comparision made between corresponding elements in X and Y, the boolean tensor we get is of the same shape and size as that of X and Y

Next, we try X > Y

In [11]:
X > Y

tensor([[False, False, False, False],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]])

We similarly get a tensor containing boolean values, having the same shape and size as X or Y. 

## Exercise 2

